services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    image: meesha-frontend:latest
    container_name: meesha-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - INTERNAL_BACKEND_URL=${INTERNAL_BACKEND_URL:-http://meesha-backend:4000}
    restart: always
    networks:
      - meesha-net

networks:
  meesha-net:
    name: meesha-net
    driver: bridge
