services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: /api
    image: meesha-frontend:v6
    container_name: meesha-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api
      - NEXTAUTH_URL=http://meesha.store
      - NEXTAUTH_SECRET=cnrIbQ6ls8q51y_8ZOAQNl3up4wDewWwDZgnohXtr48
    restart: always
